<?php
/** Liang Lee View Admins
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeeViewAdmins
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File en.php
 */
 
$english = array(	
	'liang:lee:view:admins:page' => "Administrators",
	'admin:users:leeadmins' => "Lee's Admins List",
	'liang:lee:view:admins:meni' => "Add entry in site menu 'Administrators'",
	'lee:admis' => "Enable admins list page for public %s"
 );
					
add_translation("en", $english);
